baseurl         = "/"
theme           = "casper-two"
languageCode    = "en-US"
disqusShortname = ""
paginate        = 6
#SectionPagesMenu = "main"
canonifyurls    = true

[params]
  title       = "Hugo Casper Two"
  subtitle    = "Port of Casper 2.x for Hugo"
  copyright   = "Released under the MIT license."

  cover       = "img/blog-cover.jpg"
  description = "Here is a description of your site."
  metaDescription = ""
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

  twitterName = "faketryghost"
  fbName = "fakeghost"
  githubName = "eueung"

  logo = "hugo-logo.png"
  orgName = "EM"
  orgWebsite = "https://www.telematika.org"
  orgDescription = "Here is a description placeholder for your org"

  author = "EM"
  authorAvatar = "img/ghost-icon.png"
  authorLocation = "Bandung, ID"
  authorWebsite = "https://eueung.github.io"
  authorDescription = "Your description here"

  pageNotFoundTitle = "404 - Page not found"

[permalinks]
  post = "/post/:slug/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200

[[menu.main]]
  name = "Go"
  url = "/tags/golang/"
  weight = 100

[[menu.main]]
  name = "Food"
  url = "/categories/food/"
  weight = 99

[[menu.main]]
  name = "External"
  url = "https://google.com/"
  weight = 95


